### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by DimitriTuaz** [DimitriTuaz/radio-didou#12]

**Comment by paeolo** [comment]
It would be much better to use apache for https. I need to talk to dimitri.

**Comment by paeolo** [comment]
It's done. I already set up Apache2 in production but with a non-SSL site. It's because the current production code makes a non-https call to icecast status. To switch to HTTPS in production just do:
sudo a2dissite 100-radio-didou
sudo a2ensite 200-radio-didou-ssl
sudo systemctl restart apache2
