### ISSUE TITLE
[Login] Setting the cookie result in multiple cookie

### ISSUE THREAD

**Issue by DimitriTuaz** [DimitriTuaz/radio-didou#27]
On Chrome 79 on MacOS 10.14.6, the options of the `RADIO-DIDOU-AUTH` cookie create new cookies (such as the expire, normally used the change the expiry date of the `RADIO-DIDOU-AUTH` cookie). See screenshot attached
<img width="478" alt="Capture d’écran 2020-02-04 à 15 15 38" src="https://user-images.githubusercontent.com/6328946/73752643-9840ba00-4761-11ea-9def-c587a8b631ef.png">

**Comment by DimitriTuaz** [comment]
On the HTTP `login` response (captured with Chrome Dev Tools) : 
![Capture d’écran 2020-02-04 à 15 29 53](https://user-images.githubusercontent.com/6328946/73753655-4b5de300-4763-11ea-8ea3-48164f1479bc.png)

**Comment by paeolo** [comment]
okay effectivement j'ai utilisé response.setHeader, il fallait utiliser response.cookie
