### ISSUE TITLE
Current Playback must not only check Dimitri Spotify account

### ISSUE THREAD

**Issue by DimitriTuaz** [DimitriTuaz/radio-didou#7]
Must support at least : 

- Soundcloud
- "No playback currently"
- DJ Set
- Vinyl only session

**Comment by paeolo** [comment]
Deezer OK.
Spotify OK.
None. OK
Soundclound -> Il faut faire un formulaire qui doit être approuvé.. Et en ce moment il n'approuve plus car ils sont surchargé..
